from datetime import date, datetime
from decimal import Decimal
from functools import partial
import logging
from typing import Any, Callable, Dict, List, Optional, Tuple

from src.core.storage_models import TenantDatabaseManager
from src.skills.invoicing import InvoicingSkill, LineItem
from src.skills.google_calendar import (
    API_DISABLED_MESSAGE,
    CalendarApiDisabled,
    CalendarNotShared,
    GoogleCalendarBooking,
    SlotUnavailable,
    not_shared_message,
)
from src.skills.memory_tree import TenantMemoryTree
from src.skills.website_seo import build_seo_report

logger = logging.getLogger("tools_registry")


async def _execute_create_invoice(
    tenant_id: str,
    base_data_dir: str,
    customer_name: str,
    amount: float,
    description: str = "Standard services",
    deposit_percentage: float = 0.0,
    client_contact: Optional[str] = None,
    created_invoices: Optional[List[str]] = None,
) -> str:
    """Generates and saves a draft invoice. `amount` is the TOTAL the customer pays, VAT included."""
    logger.info(f"[TOOL INVOICE] Tenant={tenant_id} | Total={amount} AED (VAT inclusive)")
    try:
        db_mgr = TenantDatabaseManager(tenant_id=tenant_id, base_dir=base_data_dir)
        next_invoice_num = await db_mgr.get_next_invoice_number()

        # 1. Instantiate InvoicingSkill configured for tenant with AED
        skill = InvoicingSkill(tenant_id=tenant_id, default_currency="AED")
        try:
            seq_num = int(next_invoice_num.rsplit("-", 1)[1])
            skill._counter = seq_num - 1
        except (IndexError, ValueError):
            pass

        # 2. Construct line item: the amount typed is the total, 5% UAE VAT is included in it
        items = [
            LineItem(
                description=description,
                quantity=Decimal("1.0"),
                unit_price=Decimal(str(amount)),
                tax_rate=Decimal("0.05"),
                price_includes_tax=True,
            )
        ]

        # 3. Generate structured draft invoice with verified database sequence number
        draft = skill.generate_invoice(
            client_name=customer_name,
            client_contact=client_contact or "",
            items=items,
            deposit_percentage=Decimal(str(deposit_percentage)),
            notes="Draft generated by AI assistant.",
        )
        draft.invoice_number = next_invoice_num

        # 4. Persist invoice draft in tenant SQLite database (plain INSERT)
        draft_record = {
            "invoice_number": draft.invoice_number,
            "tenant_id": tenant_id,
            "client_name": draft.client_name,
            "client_contact": draft.client_contact,
            "currency": draft.currency,
            "subtotal": float(draft.subtotal),
            "tax_amount": float(draft.total_tax),
            "grand_total": float(draft.grand_total),
            "deposit_percentage": float(draft.deposit_percentage),
            "required_deposit": float(draft.required_deposit),
            "balance_due": float(draft.balance_due),
            "status": "draft",
            "notes": draft.notes,
            "description": description,
        }
        await db_mgr.save_invoice_draft(draft_record)
        if created_invoices is not None:
            created_invoices.append(draft.invoice_number)

        # 5. Return honest, explicit status that this is a draft not yet sent
        reply_lines = [
            f"Draft invoice generated: {draft.invoice_number}",
            f"Client: {draft.client_name}",
            f"Total (incl. 5% VAT): {draft.currency} {draft.grand_total:,.2f}",
            f"Net amount: {draft.currency} {draft.subtotal:,.2f}",
            f"VAT (5%): {draft.currency} {draft.total_tax:,.2f}",
        ]
        if draft.required_deposit > Decimal("0.00"):
            reply_lines.append(
                f"Required Deposit ({draft.deposit_percentage:.0f}%): {draft.currency} {draft.required_deposit:,.2f}"
            )
            reply_lines.append(f"Balance Due: {draft.currency} {draft.balance_due:,.2f}")

        reply_lines.append("Status: Draft invoice — not sent to client. A PDF goes to the owner for approval.")
        return "\n".join(reply_lines)

    except Exception as e:
        logger.error(f"[TOOL INVOICE ERROR] Tenant={tenant_id}: {e}", exc_info=True)
        return "Failed to generate draft invoice due to an internal error."


async def _execute_search_memory(
    tenant_id: str,
    base_data_dir: str,
    query: str,
) -> str:
    """Internal implementation for searching verified business facts in Memory Tree."""
    logger.info(f"[TOOL MEMORY] Tenant={tenant_id} | Searching query: {query}")
    try:
        memory = TenantMemoryTree(tenant_id=tenant_id, base_data_dir=base_data_dir)
        await memory.initialize()
        results = await memory.search_memory(query=query, limit=3)
        if not results:
            return "No matching business policies or records found."
        formatted = "\n".join(f"- {r.get('content', '')}" for r in results)
        return f"Verified Records Found:\n{formatted}"
    except Exception as e:
        logger.error(f"[TOOL MEMORY ERROR] Tenant={tenant_id}: {e}", exc_info=True)
        return "Failed to search business memory records."


def _parse_day(value: str) -> date:
    return datetime.strptime(value.strip(), "%Y-%m-%d").date()


def _calendar(profile: Dict[str, Any]) -> GoogleCalendarBooking:
    return GoogleCalendarBooking(
        calendar_id=profile["google_calendar_id"],
        timezone=profile.get("timezone") or "Asia/Dubai",
        business_hours=profile.get("business_hours") or "09:00-18:00",
        slot_minutes=int(profile.get("appointment_minutes") or 60),
    )


async def _execute_check_availability(profile: Dict[str, Any], date: str) -> str:
    try:
        day = _parse_day(date)
        slots = await _calendar(profile).free_slots(day)
    except ValueError:
        return "Please give the date as YYYY-MM-DD."
    except CalendarNotShared:
        return not_shared_message()
    except CalendarApiDisabled:
        return API_DISABLED_MESSAGE
    except Exception as e:
        logger.error(f"[TOOL CALENDAR] availability failed: {e}", exc_info=True)
        return "I couldn't check the calendar right now."
    label = day.strftime("%A %d %B %Y")
    if not slots:
        return f"No free slots on {label} within business hours."
    times = ", ".join(start.strftime("%H:%M") for start, _ in slots)
    return f"Free slots on {label}: {times}"


async def _execute_book_appointment(
    profile: Dict[str, Any],
    customer_name: str,
    date: str,
    time: str,
    service: str = "Appointment",
    duration_minutes: Optional[int] = None,
    customer_phone: str = "",
) -> str:
    calendar = None
    try:
        calendar = _calendar(profile)
        start = datetime.strptime(f"{date.strip()} {time.strip()}", "%Y-%m-%d %H:%M")
        booking = await calendar.book(
            customer_name=customer_name,
            start=start,
            duration_minutes=int(duration_minutes or calendar.slot_minutes),
            service=service or "Appointment",
            customer_phone=customer_phone,
            booked_by=profile.get("booked_by", ""),
        )
    except ValueError:
        return "Please give the date as YYYY-MM-DD and the time as HH:MM (24-hour)."
    except SlotUnavailable as e:
        return f"Not booked: {e}"
    except CalendarNotShared:
        return not_shared_message()
    except CalendarApiDisabled:
        return API_DISABLED_MESSAGE
    except Exception as e:
        logger.error(f"[TOOL CALENDAR] booking failed: {e}", exc_info=True)
        return "I couldn't book that right now. Nothing was added to the calendar."
    return (
        f"Booked: {service or 'Appointment'} for {customer_name} on "
        f"{booking['start'].strftime('%A %d %B %Y')}, {booking['start'].strftime('%H:%M')}-"
        f"{booking['end'].strftime('%H:%M')}. It is now in the business Google Calendar."
    )


async def _execute_list_appointments(profile: Dict[str, Any], date: str) -> str:
    try:
        day = _parse_day(date)
        events = await _calendar(profile).events_on(day)
    except ValueError:
        return "Please give the date as YYYY-MM-DD."
    except CalendarNotShared:
        return not_shared_message()
    except CalendarApiDisabled:
        return API_DISABLED_MESSAGE
    except Exception as e:
        logger.error(f"[TOOL CALENDAR] listing failed: {e}", exc_info=True)
        return "I couldn't read the calendar right now."
    label = day.strftime("%A %d %B %Y")
    if not events:
        return f"Nothing booked on {label}."
    lines = [
        f"- {e['start'].strftime('%H:%M')}-{e['end'].strftime('%H:%M')} {e['summary']}" if e["start"]
        else f"- All day: {e['summary']}"
        for e in events
    ]
    return f"Appointments on {label}:\n" + "\n".join(lines)


async def _execute_seo_report(profile: Dict[str, Any], focus: str = "") -> str:
    return await build_seo_report(profile.get("website_url"), profile.get("search_console_property"))


CALENDAR_TOOL_SCHEMAS = [
    {
        "type": "function",
        "function": {
            "name": "check_availability",
            "description": "List free appointment slots on a date in the business Google Calendar (within business hours).",
            "parameters": {
                "type": "object",
                "properties": {"date": {"type": "string", "description": "Date as YYYY-MM-DD."}},
                "required": ["date"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "book_appointment",
            "description": (
                "Book an appointment in the business Google Calendar. Use only when the customer name, date and "
                "time are clear; it refuses times that are taken, past, or outside business hours."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "customer_name": {"type": "string", "description": "Customer's name."},
                    "date": {"type": "string", "description": "Date as YYYY-MM-DD."},
                    "time": {"type": "string", "description": "Start time as HH:MM, 24-hour, business local time."},
                    "service": {"type": "string", "description": "What the appointment is for, e.g. Deep cleaning."},
                    "duration_minutes": {"type": "integer", "description": "Optional length in minutes."},
                    "customer_phone": {"type": "string", "description": "Optional customer phone number."},
                },
                "required": ["customer_name", "date", "time"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "list_appointments",
            "description": "List what is booked on a date in the business Google Calendar.",
            "parameters": {
                "type": "object",
                "properties": {"date": {"type": "string", "description": "Date as YYYY-MM-DD."}},
                "required": ["date"],
            },
        },
    },
]

SEO_TOOL_SCHEMA = {
    "type": "function",
    "function": {
        "name": "website_seo_report",
        "description": (
            "Run Google's website check (speed, SEO basics) on the business website and, if connected, "
            "real Google Search numbers. Use when asked how the website or SEO is doing."
        ),
        # Gemini rejects function schemas with no properties, so this tool takes an optional focus.
        "parameters": {
            "type": "object",
            "properties": {
                "focus": {"type": "string", "description": "Optional: what the user wants to know, e.g. speed."},
            },
        },
    },
}


def get_scoped_tools(
    tenant_id: str,
    base_data_dir: str = "/app/data/tenants",
    created_invoices: Optional[List[str]] = None,
    profile: Optional[Dict[str, Any]] = None,
) -> Tuple[List[Dict[str, Any]], Dict[str, Callable]]:
    """Returns OpenAI/LiteLLM tool definitions and executable callables with tenant_id bound.

    The LLM schema NEVER exposes tenant_id. The dispatcher injects tenant_id securely.
    """
    tools_schema = [
        {
            "type": "function",
            "function": {
                "name": "create_invoice",
                "description": (
                    "Create a draft invoice in AED. The amount is the TOTAL the customer pays and already "
                    "includes 5% VAT (e.g. 'Invoice Ali 2,500 AED' -> amount 2500). "
                    "This saves a draft and does NOT send anything to the client."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "customer_name": {
                            "type": "string",
                            "description": "Full name or business name of the client being billed.",
                        },
                        "amount": {
                            "type": "number",
                            "description": "Total amount in AED INCLUDING 5% VAT, exactly as the user stated it. Do not add VAT on top.",
                        },
                        "description": {
                            "type": "string",
                            "description": "Line-item description of services or products.",
                        },
                        "deposit_percentage": {
                            "type": "number",
                            "description": "Optional upfront deposit percentage (e.g. 50.0 for 50%). Default is 0.0.",
                        },
                        "client_contact": {
                            "type": "string",
                            "description": "Optional phone number or contact identifier of the client.",
                        },
                    },
                    "required": ["customer_name", "amount"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "search_business_memory",
                "description": "Search verified business policies, pricing sheets, and past records.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "The policy or topic to search (e.g. cancellation policy, hourly rate).",
                        },
                    },
                    "required": ["query"],
                },
            },
        },
    ]

    # Map function names to server-bound callables
    callables_map = {
        "create_invoice": partial(
            _execute_create_invoice, tenant_id, base_data_dir, created_invoices=created_invoices
        ),
        "search_business_memory": partial(_execute_search_memory, tenant_id, base_data_dir),
    }

    profile = profile or {}
    if profile.get("google_calendar_id"):
        tools_schema.extend(CALENDAR_TOOL_SCHEMAS)
        callables_map["check_availability"] = partial(_execute_check_availability, profile)
        callables_map["book_appointment"] = partial(_execute_book_appointment, profile)
        callables_map["list_appointments"] = partial(_execute_list_appointments, profile)
    tools_schema.append(SEO_TOOL_SCHEMA)
    callables_map["website_seo_report"] = partial(_execute_seo_report, profile)

    return tools_schema, callables_map