from decimal import Decimal
from functools import partial
import logging
from typing import Any, Callable, Dict, List, Optional, Tuple

from src.core.storage_models import TenantDatabaseManager
from src.skills.invoicing import InvoicingSkill, LineItem
from src.skills.memory_tree import TenantMemoryTree

logger = logging.getLogger("tools_registry")


async def _execute_create_invoice(
    tenant_id: str,
    base_data_dir: str,
    customer_name: str,
    amount: float,
    description: str = "Standard services",
    deposit_percentage: float = 0.0,
    client_contact: Optional[str] = None,
) -> str:
    """Internal implementation for generating and saving customer invoice drafts with database sequence numbering."""
    logger.info(
        f"[TOOL INVOICE] Tenant={tenant_id} | Customer={customer_name} | Amount={amount} AED | Desc={description}"
    )
    try:
        db_mgr = TenantDatabaseManager(tenant_id=tenant_id, base_dir=base_data_dir)
        next_invoice_num = await db_mgr.get_next_invoice_number()

        # 1. Instantiate InvoicingSkill configured for tenant with AED
        skill = InvoicingSkill(tenant_id=tenant_id, default_currency="AED")
        try:
            seq_num = int(next_invoice_num.rsplit("-", 1)[1])
            skill._counter = seq_num - 1
        except (IndexError, ValueError):
            pass

        # 2. Construct line item with 5% UAE VAT
        items = [
            LineItem(
                description=description,
                quantity=Decimal("1.0"),
                unit_price=Decimal(str(round(amount, 2))),
                tax_rate=Decimal("0.05"),
            )
        ]

        # 3. Generate structured draft invoice with verified database sequence number
        draft = skill.generate_invoice(
            client_name=customer_name,
            client_contact=client_contact or "",
            items=items,
            deposit_percentage=Decimal(str(deposit_percentage)),
            notes="Draft generated by AI assistant.",
        )
        draft.invoice_number = next_invoice_num

        # 4. Persist invoice draft in tenant SQLite database (plain INSERT)
        draft_record = {
            "invoice_number": draft.invoice_number,
            "tenant_id": tenant_id,
            "client_name": draft.client_name,
            "client_contact": draft.client_contact,
            "currency": draft.currency,
            "subtotal": float(draft.subtotal),
            "tax_amount": float(draft.total_tax),
            "grand_total": float(draft.grand_total),
            "deposit_percentage": float(draft.deposit_percentage),
            "required_deposit": float(draft.required_deposit),
            "balance_due": float(draft.balance_due),
            "status": "draft",
            "notes": draft.notes,
        }
        await db_mgr.save_invoice_draft(draft_record)

        # 5. Return honest, explicit status that this is a draft not yet sent
        reply_lines = [
            f"Draft invoice generated: {draft.invoice_number}",
            f"Client: {draft.client_name}",
            f"Subtotal: {draft.currency} {draft.subtotal:.2f}",
            f"VAT (5%): {draft.currency} {draft.total_tax:.2f}",
            f"Grand Total: {draft.currency} {draft.grand_total:.2f}",
        ]
        if draft.required_deposit > Decimal("0.00"):
            reply_lines.append(
                f"Required Deposit ({draft.deposit_percentage:.0f}%): {draft.currency} {draft.required_deposit:.2f}"
            )
            reply_lines.append(f"Balance Due: {draft.currency} {draft.balance_due:.2f}")

        reply_lines.append("Status: Draft invoice — not sent to client.")
        return "\n".join(reply_lines)

    except Exception as e:
        logger.error(f"[TOOL INVOICE ERROR] Tenant={tenant_id}: {e}", exc_info=True)
        return "Failed to generate draft invoice due to an internal error."


async def _execute_search_memory(
    tenant_id: str,
    base_data_dir: str,
    query: str,
) -> str:
    """Internal implementation for searching verified business facts in Memory Tree."""
    logger.info(f"[TOOL MEMORY] Tenant={tenant_id} | Searching query: {query}")
    try:
        memory = TenantMemoryTree(tenant_id=tenant_id, base_data_dir=base_data_dir)
        await memory.initialize()
        results = await memory.search_memory(query=query, limit=3)
        if not results:
            return "No matching business policies or records found."
        formatted = "\n".join(f"- {r.get('content', '')}" for r in results)
        return f"Verified Records Found:\n{formatted}"
    except Exception as e:
        logger.error(f"[TOOL MEMORY ERROR] Tenant={tenant_id}: {e}", exc_info=True)
        return "Failed to search business memory records."


def get_scoped_tools(
    tenant_id: str,
    base_data_dir: str = "/app/data/tenants",
) -> Tuple[List[Dict[str, Any]], Dict[str, Callable]]:
    """Returns OpenAI/LiteLLM tool definitions and executable callables with tenant_id bound.

    The LLM schema NEVER exposes tenant_id. The dispatcher injects tenant_id securely.
    """
    tools_schema = [
        {
            "type": "function",
            "function": {
                "name": "create_invoice",
                "description": "Create a draft invoice for services or products in AED. This saves a draft and does NOT send anything to the client.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "customer_name": {
                            "type": "string",
                            "description": "Full name or business name of the client being billed.",
                        },
                        "amount": {
                            "type": "number",
                            "description": "Total monetary subtotal amount before tax in AED.",
                        },
                        "description": {
                            "type": "string",
                            "description": "Line-item description of services or products.",
                        },
                        "deposit_percentage": {
                            "type": "number",
                            "description": "Optional upfront deposit percentage (e.g. 50.0 for 50%). Default is 0.0.",
                        },
                        "client_contact": {
                            "type": "string",
                            "description": "Optional phone number or contact identifier of the client.",
                        },
                    },
                    "required": ["customer_name", "amount"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "search_business_memory",
                "description": "Search verified business policies, pricing sheets, and past records.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "The policy or topic to search (e.g. cancellation policy, hourly rate).",
                        },
                    },
                    "required": ["query"],
                },
            },
        },
    ]

    # Map function names to server-bound callables
    callables_map = {
        "create_invoice": partial(_execute_create_invoice, tenant_id, base_data_dir),
        "search_business_memory": partial(_execute_search_memory, tenant_id, base_data_dir),
    }

    return tools_schema, callables_map